name: Deploy to BCR

on:
  push:

jobs:
  deploy-to-bcr:
    runs-on: macos
    steps:
      - uses: actions/checkout@v3

      - run: docker build -t bp ./.github/workflows/

      - run: docker run -i --device=/dev/kvm --cap-add=net_admin --network host bp
