name: Deploy to BCR

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy-to-bcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Balena
        uses: balena-io-experimental/balena.yml-action@main
        with:
          sync_readme: true
          sync_tag: true

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: maggie0002/test-block
