name: Deploy to BCR

on:
  push:

jobs:
  deploy-to-bcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check
        run: cat balena.yml

      - name: Update balena.yml
        uses: balena-io-experimental/balena.yml-action@main
        with:
          sync_readme: false
          sync_tag: false

      - name: Check
        run: cat balena.yml

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: maggie0002/test-block
