# A test yml file used for development on Mac M1 stored here for reference
templates:
  standard:
    machine: virt,accel=hvf,highmem=off
    # qemu-system-aarch64 defaults to cortex-a15, so -cpu is required for 64-bit OSes
    cpu:  cortex-a53
    smp: cores=4
    m: 2G
    drive:
      - if: pflash
        format: raw
        unit: 0
        file: usr/share/edk2-armvirt/aarch64/QEMU_CODE.fd
      - if: virtio
        format: raw
        unit: 0
        file: generic-aarch64-2.99.26-v14.0.8.img
    #net:
    #  - nic:
    #    model: virtio
    #    macaddr: "{{macAddress}}"
    #  - bridge:
    #    br: qemu0
    # Hide output of virtual machine
    #chardev: null,id=id
    #serial: none
    monitor: none
    nographic:

guests:
  - template: standard
    arch: aarch64
    count: 1
